### ISSUE TITLE
Search Not Displaying Plugin as Available for Android Studio

### ISSUE THREAD

**Issue by RodrigoQuesadaDev** [anton-dev-ua/PipeTableFormatter#3]
Currently JetBrains' site (and search box on IDE) doesn't show any results for this plugin: https://plugins.jetbrains.com/?androidstudio

**Comment by RodrigoQuesadaDev** [comment]
I created a PR here: https://github.com/anton-dev-ua/PipeTableFormatter/pull/4

This is a cool plugin, so thank you! :)

**Comment by anton-dev-ua** [comment]
Included in 0.3.1
Thanks for this change!
