### ISSUE TITLE
comments get converted into tables

### ISSUE THREAD

**Issue by pgomulka** [anton-dev-ua/PipeTableFormatter#5]
Hi,
I found following problem
for that snippet:

And some step:
| columnName  |
| columnValue |

!-- comment, comment comment.
!-- omment, comment comment.
And some other step
| columnName  |
| columnValue |

it will become formatted into : 
And some step:
| columnName  |
| columnValue |

| !-- comment | comment comment. |
| !-- omment  | comment comment. |
And some other step
| columnName  |
| columnValue |

so this is obviously because commas are changed into pipes. Is it possible to disable this comma to pipe changes?

**Comment by anton-dev-ua** [comment]
Hi, 

Could you please describe whole scenario? Which command was used for formatting?

Thanks.

**Comment by pgomulka** [comment]
the snipped from first post and then "format all"
 it then treats comment section as separated with commas, and changes that to pipes

**Comment by anton-dev-ua** [comment]
Thanks for reported issue!
Fixed in 0.4.1
