### ISSUE TITLE
Incorrect behavior when using JSON values

### ISSUE THREAD

**Issue by RodrigoQuesadaDev** [anton-dev-ua/PipeTableFormatter#6]
If I have this table

    |header1|header2|
    |value1|[{a:1, b:1}, {a:1, b:1}, {a:1, b:1}]|
    |value2|[{a:2, b:2}, {a:2, b:2}, {a:2, b:2}]|

and then format it, then I get

    | header1|header2 |      |      |      |      |       |
    | value1|[{a:1    | b:1} | {a:1 | b:1} | {a:1 | b:1}] |
    | value2|[{a:2    | b:2} | {a:2 | b:2} | {a:2 | b:2}] |

instead of

    | header1 | header2                              |
    | value1  | [{a:1, b:1}, {a:1, b:1}, {a:1, b:1}] |
    | value2  | [{a:2, b:2}, {a:2, b:2}, {a:2, b:2}] |

**Comment by anton-dev-ua** [comment]
Thanks for reporting an issue!
I will fix this.

**Comment by anton-dev-ua** [comment]
fixed in 0.4.2

**Comment by RodrigoQuesadaDev** [comment]
Awesome, thank you!
