### ISSUE TITLE
Row comments incorrectly formatted

### ISSUE THREAD

**Issue by RodrigoQuesadaDev** [anton-dev-ua/PipeTableFormatter#7]
Hi, currently comments between rows get incorrectly formatted (rows are commented using '|--' http://jbehave.org/reference/stable/faq.html). So the table

    |Header|
    |--a comment--|
    |value|
    |--another comment--|

gets formatted to

    | Header              |
    | --a comment--       |
    | value               |
    | --another comment-- |

instead of getting formatted to

    | Header              |
    |-- a comment       --|
    | value               |
    |-- another comment --|

Cheers,
Rodrigo

**Comment by anton-dev-ua** [comment]
Thanks,
resolved in version 0.5.0

**Comment by RodrigoQuesadaDev** [comment]
Awesome, thank you!!
